/* tslint:disable */
/* eslint-disable */
/**
 * Tacto Codechallange API
 * Dummy API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Article,
    ArticleFromJSON,
    ArticleToJSON,
} from '../models';

/**
 * ArticlesApi - interface
 * 
 * @export
 * @interface ArticlesApiInterface
 */
export interface ArticlesApiInterface {
    /**
     * 
     * @summary fetches all articles in the organization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApiInterface
     */
    fetchArticlesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Article>>>;

    /**
     * fetches all articles in the organization
     */
    fetchArticles(initOverrides?: RequestInit): Promise<Array<Article>>;

}

/**
 * 
 */
export class ArticlesApi extends runtime.BaseAPI implements ArticlesApiInterface {

    /**
     * fetches all articles in the organization
     */
    async fetchArticlesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Article>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/articles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ArticleFromJSON));
    }

    /**
     * fetches all articles in the organization
     */
    async fetchArticles(initOverrides?: RequestInit): Promise<Array<Article>> {
        const response = await this.fetchArticlesRaw(initOverrides);
        return await response.value();
    }

}
