default: true

MD013:
  # Number of characters
  line_length: 100
  tables: false
  code_blocks: false

# code-block-style, disabled to allow mixed usage of fenced and indented style
MD046:
  style: "fenced"

MD024:
  allow_different_nesting: true
