/* tslint:disable */
/* eslint-disable */
/**
 * Tacto Codechallange API
 * Dummy API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     *
     * @type {number}
     * @memberof Organization
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof Organization
     */
    name: string;
    /**
     *
     * @type {Array<number>}
     * @memberof Organization
     */
    supplierIds: Array<number>;
    /**
     *
     * @type {Array<number>}
     * @memberof Organization
     */
    customerIds: Array<number>;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'supplierIds': json['supplier_ids'],
        'customerIds': json['customer_ids'],
    };
}

export function OrganizationToJSON(value?: Organization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'name': value.name,
        'supplier_ids': value.supplierIds,
        'customer_ids': value.customerIds,
    };
}
